### ISSUE TITLE
fastkml does not install from requirements.txt

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#21]
doing `pip install -r requirements.txt` in a virtualenv does not work because `fastkml` demands other things are installed.

**Comment by IanHopkinson** [comment]
```
Downloading/unpacking fastkml==0.9 (from -r requirements.txt (line 6))
  Downloading fastkml-0.9.tar.gz (67kB): 67kB downloaded
  Running setup.py egg_info for package fastkml
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/venv/build/fastkml/setup.py", line 6, in <module>
        import fastkml
      File "fastkml/__init__.py", line 18, in <module>
        from .kml import KML, Document, Folder, Placemark
      File "fastkml/kml.py", line 37, in <module>
        from .geometry import Geometry
      File "fastkml/geometry.py", line 38, in <module>
        from pygeoif.geometry import Point, LineString, Polygon
    ImportError: No module named pygeoif.geometry
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/venv/build/fastkml/setup.py", line 6, in <module>

    import fastkml

  File "fastkml/__init__.py", line 18, in <module>

    from .kml import KML, Document, Folder, Placemark

  File "fastkml/kml.py", line 37, in <module>

    from .geometry import Geometry

  File "fastkml/geometry.py", line 38, in <module>

    from pygeoif.geometry import Point, LineString, Polygon

ImportError: No module named pygeoif.geometry
```
