### ISSUE TITLE
Can't handle Google's KML_samples file

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#22]
Cannot handle this KML file:

https://developers.google.com/kml/documentation/KML_Samples.kml

**Comment by IanHopkinson** [comment]
```
WARNING:fastkml.kml:No geometries found
Traceback (most recent call last):
  File "tool/geojson.py", line 204, in <module>
    main()
  File "tool/geojson.py", line 43, in main
    return convert_one(url)
  File "tool/geojson.py", line 55, in convert_one
    parse_kml(response.content)
  File "tool/geojson.py", line 138, in parse_kml
    geometry = feature.geometry
AttributeError: 'Folder' object has no attribute 'geometry'
```

**Comment by IanHopkinson** [comment]
The problem is that KML_samples uses `Document`, basically `features` can exist at the top level of a file, or they can exist inside `Folder`s which can exist inside `Documents`
`Document`->`Folders`->`Features`

**Comment by IanHopkinson** [comment]
This is handled in 32c8637 at the command line but does not recurse into documents/folders found below the top level
