### ISSUE TITLE
Another KML file we can't parse

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#23]
This one fails with:
https://dl.dropboxusercontent.com/u/21886071/countries_world.kml

```
Traceback (most recent call last):
  File "geojson.py", line 230, in <module>
    main()
  File "geojson.py", line 51, in main
    return convert_one(url)
  File "geojson.py", line 69, in convert_one
    features, polygons = parse_kml(response.content, features, polygons)
  File "geojson.py", line 125, in parse_kml
    folders.append(f.features())
AttributeError: 'Placemark' object has no attribute 'features'
```

**Comment by IanHopkinson** [comment]
Fixed by 9afc796
